version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    cooldown:
      default-days: 3
    schedule:
      interval: daily
      time: "03:00"
      timezone: Europe/London
    open-pull-requests-limit: 5
    groups:
      minor-and-patch:
        update-types: # only group minor and patch updates together
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/" # Location of workflow files
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
