CREATE SCHEMA IF NOT EXISTS product_;

CREATE TABLE product_.lao_crns (id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, crn TEXT, version INTEGER, last_updated TIMESTAMP);

CREATE TABLE product_.lao_exclusions (crn_user_id TEXT PRIMARY KEY, crn TEXT, user_id TEXT, reason TEXT, since TIMESTAMPTZ, until TIMESTAMPTZ);

CREATE TABLE product_.lao_restrictions (crn_user_id TEXT PRIMARY KEY, crn TEXT, user_id TEXT, reason TEXT, since TIMESTAMPTZ, until TIMESTAMPTZ);

-- Emulate redshift as closely as possible which does not enforce PKEY constraints
ALTER TABLE product_.lao_crns DROP CONSTRAINT lao_crns_pkey;
ALTER TABLE product_.lao_restrictions DROP CONSTRAINT lao_restrictions_pkey;
ALTER TABLE product_.lao_exclusions DROP CONSTRAINT lao_exclusions_pkey;
